apiVersion: v1
kind: ConfigMap
metadata:
  name: settings-todo-app
data:
  DB_HOST : postgres
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_PORT : '5432'
  DB_NAME : todos_db
  DB_VERSION : '10.4'
