apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo-app
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  strategy: {}
  template:
    metadata:
      labels:
        app: todo-app
    spec:  
      containers:
      - image: luisgo/todo-app
        name: todo-app
        envFrom:
          - configMapRef:
              name: settings-todo-app
        resources: {}
status: {}