pipeline{
    agent any
    stages{
        stage('Compile'){   
            steps{
                
             sh '''
                chmod +x gradlew
                gradle wrapper
                /CICD/exercise1/gradlew compileJava'''
            }
        }
        stage('Unit Test'){
            steps{

                sh '''
                chmod +x gradlew
                ./gradlew test
                '''
            }
        }
    
    }
}
