stages:
    - build
    - test
    - build_docker
    - deploy    

maven:build:
  image: maven:3-openjdk-8
  stage: build
  script:
    - mvn clean package -DskipTests=true
  artifacts:
    when: always
    paths:
      - target/spring-boot-hello-world-1.0.0-SNAPSHOT.jar

maven:test:
  image: maven:3-openjdk-8
  stage: test
  script:
    - mvn verify
    - mvn test

docker:build:
    stage: build_docker
    before_script:
        - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY/$CI_PROJECT_PATH
    script:
        - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH/exercise1:$CI_COMMIT_SHA .
        - docker push $CI_REGISTRY/$CI_PROJECT_PATH/exercise1:$CI_COMMIT_SHA

docker:deploy:
  stage: deploy
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY/$CI_PROJECT_PATH
  script:
    - docker run --name "springapp" -d -p 8080:8080 $CI_REGISTRY/$CI_PROJECT_PATH/exercise1:$CI_COMMIT_SHA
